name: Daily Weather Ingestion

on:
  schedule:
    - cron: '0 5 * * *'   # 5am UTC = 7am Stockholm
  workflow_dispatch:       # allow manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests azure-storage-blob python-dotenv snowflake-connector-python

      - name: Run ingestion script
        env:
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          SNOWFLAKE_USER:          ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD:      ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT:       ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: python ingest_weather.py
